%extract features from chosen target and
%stores it in a matlab variable (proc_target)
%must pass as arguments the name of the file, generated by ROS 
%log file from process_target, and the id of the desired subject

%function [robot,proc_target]=leader_features(file,target_id)
function [proc_target]=leader_features(file,target_id)

% input file format: 
% 1: id
% 2: good/bad tag
% 3: time
% 4: pos x
% 5: pos y
% 6: vel
% 7: theta
% 8: pos diff
% 9: head diff
%10: angle 2 robot 
%11: velocity diff 

%printf("%d,%d,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f,%.2f\n",
%         target_id, badLeader, time_elapsed.toSec(),
%         target_x, target_y, target_vel, target_theta,
%         position_diff, heading_diff, angle_to_robot, velocity_diff);

% output file format: 
% 1: time
% 2: good/bad tag
% 3: mean vel                 1
% 4: mean vel diff            2
% 5: mean head diff           3
% 6: angle 2 robot            4
% 7: mean dist 2 robot        5

%initialize vars
begin_sweep = 1;
end_sweep = 1;
counter = 1;

mean_fig = figure; hold on; grid on;

%load and rearrange targets file
list = load(file);
range = max(list(:,1)) + 2;
cm = jet(range);

figure,hold; %axis square;
for i = 1:length(list);
    if(list(i,1)==-1)
       plot3(list(i,4),list(i,5),list(i,3),'bo');
%        plot3(list(i,4),list(i,5),list(i,3),'o','color',cm((list(i,1)+2),:));
    elseif(list(i,1)==target_id)
       plot3(list(i,4),list(i,5),list(i,3),'ro');
    end
end
%axis equal;



list = sortrows(list);

% separate target from robot
while counter < length(list)
    while list(begin_sweep,1) == list(end_sweep,1)
        end_sweep = end_sweep + 1;
        counter = counter + 1;
        if counter > length(list) 
            break
        end
    end
    
    %only pick one target, according to input of function
    switch list(begin_sweep,1)
        case -1
            robot = list(begin_sweep:end_sweep-1,:);
        case target_id
            target = list(begin_sweep:end_sweep-1,:);
    end
    
    begin_sweep = end_sweep;
end

% filter data
proc_target(length(target),7) = 0;
proc_target(:,1) = target(:,3);
proc_target(:,2) = target(:,2);
proc_target(:,6) = target(:,10); %angle 2 robot


proc_target(:,3) = target(:,6);  %vel
proc_target(:,4) = target(:,11); %vel diff
proc_target(:,5) = target(:,9);  %head diff
proc_target(:,6) = target(:,10); %angle 2 robot
proc_target(:,7) = target(:,8);  %pos diff (dist)
% for i=1:length(target)
%     winsize = 50;
%     while(i-winsize <= 0) %not enough past info
%         winsize = winsize - 1;
%     end
%     proc_target(i,3) = mean(target(i-winsize:i,6));  %vel
%     proc_target(i,4) = mean(target(i-winsize:i,11)); %vel diff
%     proc_target(i,5) = mean(target(i-winsize:i,9));  %head diff
%     %proc_target(i,6) = mean(target(i-winsize:i,10)); %angle 2 robot
%     proc_target(i,7) = mean(target(i-winsize:i,8));  %pos diff (dist)
% end
    

    
%%%%%%%%% PLOTTING %%%%%%%%%%%%

%removing angle jump
% robot(:,7) = unwrap(robot(:,7));
% robot(:,9) = unwrap(robot(:,9));
% robot(:,10) = unwrap(robot(:,10));
% target(:,7) = unwrap(target(:,7));
% target(:,9) = unwrap(target(:,9));
% target(:,10) = unwrap(target(:,10));
%proc_target(:,5) = unwrap(proc_target(:,5));
%proc_target(:,6) = unwrap(proc_target(:,6));

% if(max(proc_target(:,5)>pi))
%     proc_target(:,5) = proc_target(:,5) - 2*pi;
% elseif(min(proc_target(:,5)<-pi))
%     proc_target(:,5) = proc_target(:,5) + 2*pi;
% end

%plot good/bad leader index
tag = find(diff(proc_target(:,2)));

figure(mean_fig);
plot(proc_target(:,1),proc_target(:,3),'b-');
plot(proc_target(:,1),proc_target(:,4),'r-');
plot(proc_target(:,1),proc_target(:,5),'k-');
plot(proc_target(:,1),proc_target(:,6),'g-');
plot(proc_target(:,1),proc_target(:,7),'y-');
legend('vel','vel diff','head diff','angle', 'distance',...
    'Location','NorthWest');
title('mean features from target 2 robot');
if ~isempty(tag)
    line([proc_target(tag,1) proc_target(tag,1)],[0 5])
    %plot(proc_target(tag,1),0:0.1:5);
end

%proc_target = crop_features(proc_target);

figure(mean_fig);
plot(proc_target(:,1),proc_target(:,3),'bo');
plot(proc_target(:,1),proc_target(:,4),'ro');
plot(proc_target(:,1),proc_target(:,5),'ko');
plot(proc_target(:,1),proc_target(:,6),'go');
plot(proc_target(:,1),proc_target(:,7),'yo');
legend('vel','vel diff','head diff','angle', 'distance',...
    'Location','NorthWest');
