/**************************************************************************************************
 Software License Agreement (BSD License)

 Copyright (c) 2011-2013, LAR toolkit developers - University of Aveiro - http://lars.mec.ua.pt
 All rights reserved.

 Redistribution and use in source and binary forms, with or without modification, are permitted
 provided that the following conditions are met:

  *Redistributions of source code must retain the above copyright notice, this list of
   conditions and the following disclaimer.
  *Redistributions in binary form must reproduce the above copyright notice, this list of
   conditions and the following disclaimer in the documentation and/or other materials provided
   with the distribution.
  *Neither the name of the University of Aveiro nor the names of its contributors may be used to
   endorse or promote products derived from this software without specific prior written permission.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR
 IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
 CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
***************************************************************************************************/
/* Auto-generated by genmsg_cpp for file /home/prometeu/ros/inria_wheelchair/social_filter/msg/humanPoses.msg */
#ifndef SOCIAL_FILTER_MESSAGE_HUMANPOSES_H
#define SOCIAL_FILTER_MESSAGE_HUMANPOSES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "humanPose.h"

namespace social_filter
{
template <class ContainerAllocator>
struct humanPoses_ {
  typedef humanPoses_<ContainerAllocator> Type;

  humanPoses_()
  : humans()
  {
  }

  humanPoses_(const ContainerAllocator& _alloc)
  : humans(_alloc)
  {
  }

  typedef std::vector< ::social_filter::humanPose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::social_filter::humanPose_<ContainerAllocator> >::other >  _humans_type;
  std::vector< ::social_filter::humanPose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::social_filter::humanPose_<ContainerAllocator> >::other >  humans;


  ROS_DEPRECATED uint32_t get_humans_size() const { return (uint32_t)humans.size(); }
  ROS_DEPRECATED void set_humans_size(uint32_t size) { humans.resize((size_t)size); }
  ROS_DEPRECATED void get_humans_vec(std::vector< ::social_filter::humanPose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::social_filter::humanPose_<ContainerAllocator> >::other > & vec) const { vec = this->humans; }
  ROS_DEPRECATED void set_humans_vec(const std::vector< ::social_filter::humanPose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::social_filter::humanPose_<ContainerAllocator> >::other > & vec) { this->humans = vec; }
private:
  static const char* __s_getDataType_() { return "social_filter/humanPoses"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "3e3887214c20e063a19ab3e7d9f3fb4c"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "humanPose[] humans\n\
================================================================================\n\
MSG: social_filter/humanPose\n\
Header header\n\
\n\
int8 id\n\
float32 x\n\
float32 y\n\
float32 theta\n\
float32 linear_velocity\n\
float32 angular_velocity\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, humans);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, humans);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(humans);
    return size;
  }

  typedef boost::shared_ptr< ::social_filter::humanPoses_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::social_filter::humanPoses_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct humanPoses
typedef  ::social_filter::humanPoses_<std::allocator<void> > humanPoses;

typedef boost::shared_ptr< ::social_filter::humanPoses> humanPosesPtr;
typedef boost::shared_ptr< ::social_filter::humanPoses const> humanPosesConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::social_filter::humanPoses_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::social_filter::humanPoses_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace social_filter

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::social_filter::humanPoses_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::social_filter::humanPoses_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::social_filter::humanPoses_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3e3887214c20e063a19ab3e7d9f3fb4c";
  }

  static const char* value(const  ::social_filter::humanPoses_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3e3887214c20e063ULL;
  static const uint64_t static_value2 = 0xa19ab3e7d9f3fb4cULL;
};

template<class ContainerAllocator>
struct DataType< ::social_filter::humanPoses_<ContainerAllocator> > {
  static const char* value() 
  {
    return "social_filter/humanPoses";
  }

  static const char* value(const  ::social_filter::humanPoses_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::social_filter::humanPoses_<ContainerAllocator> > {
  static const char* value() 
  {
    return "humanPose[] humans\n\
================================================================================\n\
MSG: social_filter/humanPose\n\
Header header\n\
\n\
int8 id\n\
float32 x\n\
float32 y\n\
float32 theta\n\
float32 linear_velocity\n\
float32 angular_velocity\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::social_filter::humanPoses_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::social_filter::humanPoses_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.humans);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct humanPoses_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::social_filter::humanPoses_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::social_filter::humanPoses_<ContainerAllocator> & v) 
  {
    s << indent << "humans[]" << std::endl;
    for (size_t i = 0; i < v.humans.size(); ++i)
    {
      s << indent << "  humans[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::social_filter::humanPose_<ContainerAllocator> >::stream(s, indent + "    ", v.humans[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // SOCIAL_FILTER_MESSAGE_HUMANPOSES_H

